-- MySQL Script generated by MySQL Workbench
-- Tue Oct  5 10:26:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbcurrency
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcurrency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcurrency` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbcurrency` ;

-- -----------------------------------------------------
-- Table `dbcurrency`.`example`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcurrency`.`example` ;

CREATE TABLE IF NOT EXISTS `dbcurrency`.`example` (
  `CrossOrder` VARCHAR(2) NOT NULL,
  `Kod` VARCHAR(45) NULL DEFAULT NULL,
  `Unit` VARCHAR(45) NULL DEFAULT NULL,
  `Isim` VARCHAR(45) NULL DEFAULT NULL,
  `CurrencyCode` VARCHAR(45) NULL DEFAULT NULL,
  `CurrencyName` VARCHAR(45) NULL DEFAULT NULL,
  `ForexBuying` VARCHAR(45) NULL DEFAULT NULL,
  `ForexSelling` VARCHAR(45) NULL DEFAULT NULL,
  `BanknoteBuying` VARCHAR(45) NULL DEFAULT NULL,
  `BanknoteSelling` VARCHAR(45) NULL DEFAULT NULL,
  `CrossRateUSD` VARCHAR(45) NULL DEFAULT NULL,
  `CrossRateOther` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CrossOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbcurrency`.`t0001`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcurrency`.`t0001` ;

CREATE TABLE IF NOT EXISTS `dbcurrency`.`t0001` (
  `CrossOrder` VARCHAR(2) NOT NULL,
  `Kod` VARCHAR(45) NULL DEFAULT NULL,
  `Unit` VARCHAR(45) NULL DEFAULT NULL,
  `Isim` VARCHAR(45) NULL DEFAULT NULL,
  `CurrencyCode` VARCHAR(45) NULL DEFAULT NULL,
  `CurrencyName` VARCHAR(45) NULL DEFAULT NULL,
  `ForexBuying` VARCHAR(45) NULL DEFAULT NULL,
  `ForexSelling` VARCHAR(45) NULL DEFAULT NULL,
  `BanknoteBuying` VARCHAR(45) NULL DEFAULT NULL,
  `BanknoteSelling` VARCHAR(45) NULL DEFAULT NULL,
  `CrossRateUSD` VARCHAR(45) NULL DEFAULT NULL,
  `CrossRateOther` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbcurrency`.`urls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcurrency`.`urls` ;

CREATE TABLE IF NOT EXISTS `dbcurrency`.`urls` (
  `id` INT NOT NULL,
  `Url` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
